# Generated by Django 4.0.3 on 2022-04-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='category',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='date',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='updated_at',
        ),
    ]
